using System.Globalization;
using System.Runtime.CompilerServices;
using System.Text.Json;

namespace KnowledgeApp.Data;

/// <summary>
/// Explicit prototype-only UI fixtures. These are never generated by a proposal
/// command and never authenticate a user or accept a proposal into history.
/// </summary>
public static class CodexSyntheticUiFixture
{
    private const string RootPrefix = "knowledgeapp-csharp-search-";
    private const string CategoryId = "70000000-0000-7000-8000-000000000003";
    private static readonly ConditionalWeakTable<KnowledgeDatabase, SeedState> States = new();

    public static void Seed(KnowledgeDatabase database)
    {
        ArgumentNullException.ThrowIfNull(database);
        // A reopened/restored database must not receive new demonstration files.
        if (!database.OpenInfo.Created)
        {
            return;
        }
        var root = NewPrototypeRoot(database);
        var state = States.GetValue(database, _ => new SeedState());
        lock (state)
        {
            if (state.Attempted)
            {
                return;
            }
            state.Attempted = true;

            // Fixed generated IDs prevent this helper from collecting arbitrary FAQs.
            var reviseSource = RequireGeneratedArticle(database, 1);
            var mergeSources = new[]
            {
                RequireGeneratedArticle(database, 2),
                RequireGeneratedArticle(database, 3)
            };
            var categories = database.ListCategories();
            var category = categories.SingleOrDefault(item => item.Id == CategoryId);
            if (category is null || category.Name != "セキュリティ" || category.ParentId is not null)
            {
                throw FixtureProblem();
            }
            var files = new CodexProposalFiles(database);
            EnsureFixedPath(root, files.InboxPath);
            EnsureFixedPath(root, files.DelegationsPath);
            // Never mix initial fixtures with an existing exchange, even if this
            // method was accidentally called after an earlier explicit operation.
            if (Directory.EnumerateFileSystemEntries(files.InboxPath).Any() ||
                Directory.EnumerateFileSystemEntries(files.DelegationsPath).Any())
            {
                return;
            }

            var revision = files.WriteDelegation(CodexProposalKinds.Revise, [reviseSource], categories);
            var merge = files.WriteDelegation(CodexProposalKinds.Merge, mergeSources, categories);
            var proposals = new[]
            {
                Proposal(CodexProposalKinds.Create, "合成Codex新規案", null, [],
                    "承認すると新しい下書きが作成されることを確認します。",
                    "このFAQ案はC#移行の画面確認用に生成した合成データです。内容を確認し、下書きへ取り込んでください。"),
                Proposal(CodexProposalKinds.Revise, "合成Codex修正案", revision.DelegationId, [reviseSource],
                    "承認すると選択した合成FAQのタイトル・概要・回答が更新されることを確認します。",
                    "ページング合成FAQ 01だけを修正する合成提案です。分類・公開状態・タグなどは維持されます。"),
                Proposal(CodexProposalKinds.Merge, "合成Codex統合案", merge.DelegationId, mergeSources,
                    "承認時は新しい下書きだけを作成し、統合元の合成FAQを変更しません。",
                    "ページング合成FAQ 02と03をまとめる合成提案です。下書きを確認して新着期限付きで公開し、続く確認で統合元の扱いを選択してください。")
            };
            foreach (var proposal in proposals)
            {
                CodexProposalFiles.ValidateProposal(proposal);
                files.ValidateDelegatedSources(proposal);
                WriteProposal(root, files.InboxPath, proposal);
            }
        }
    }

    private static ArticleDetail RequireGeneratedArticle(KnowledgeDatabase database, int index)
    {
        var article = database.GetArticle($"72000000-0000-7000-8000-{index:000000000000}");
        var content = SafeRichContentValidator.Validate(article.BodyDoc);
        if (article.Title != $"ページング合成FAQ {index:00}" || article.CategoryId != CategoryId ||
            article.BodyPlainText != "ページング検索の本文です。" ||
            !JsonElement.DeepEquals(article.BodyDoc, PlainBody("ページング検索の本文です。")) ||
            article.UpdatedAt != $"2026-08-{index:00}T00:00:00Z" ||
            article.Status != ArticleStatuses.Published || article.IsHidden || article.DeletedAt is not null ||
            article.MergeInfo is not null || article.Attachments.Count != 0 || content.Attachments.Count != 0)
        {
            throw FixtureProblem();
        }
        return article;
    }

    private static CodexFaqProposal Proposal(
        string kind,
        string title,
        string? delegationId,
        IReadOnlyList<ArticleDetail> sources,
        string summary,
        string body)
    {
        var requestId = Guid.CreateVersion7().ToString();
        return new CodexFaqProposal
        {
            FormatVersion = 2,
            RequestId = requestId,
            SeriesId = delegationId ?? requestId,
            CreatedAt = DateTimeOffset.UtcNow.ToString("O", CultureInfo.InvariantCulture),
            ProposalKind = kind,
            SourceArticles = sources.Select(article => new CodexSourceArticle(article.Id, article.UpdatedAt)).ToArray(),
            Faq = new CodexFaqDraft
            {
                Title = title,
                Summary = summary,
                Importance = 2,
                BodyDoc = PlainBody(body)
            },
            ExistingCategoryCandidates = kind == CodexProposalKinds.Revise ? [] :
            [
                new CodexCategoryCandidate(CategoryId, "セキュリティ", "既存の合成分類で画面操作を確認します。")
            ]
        };
    }

    private static JsonElement PlainBody(string text) => JsonSerializer.SerializeToElement(new
    {
        type = "doc",
        content = new[]
        {
            new { type = "paragraph", content = new[] { new { type = "text", text } } }
        }
    }, CodexJson.Options);

    private static string NewPrototypeRoot(KnowledgeDatabase database)
    {
        var dataDirectory = Path.GetDirectoryName(Path.GetFullPath(database.OpenInfo.DatabasePath));
        var root = dataDirectory is null ? null : Path.GetDirectoryName(dataDirectory);
        var temporaryRoot = Path.TrimEndingDirectorySeparator(Path.GetFullPath(Path.GetTempPath()));
        if (root is null || Path.GetFileName(dataDirectory) != "data" ||
            !string.Equals(Path.GetDirectoryName(root), temporaryRoot, StringComparison.OrdinalIgnoreCase))
        {
            throw FixtureProblem();
        }
        var name = Path.GetFileName(root);
        if (!name.StartsWith(RootPrefix, StringComparison.Ordinal) ||
            !Guid.TryParseExact(name[RootPrefix.Length..], "D", out _))
        {
            throw FixtureProblem();
        }
        EnsureFixedPath(root, root);
        return root;
    }

    private static void WriteProposal(string root, string inbox, CodexFaqProposal proposal)
    {
        var target = Path.Combine(inbox, proposal.RequestId + CodexProposalFiles.ProposalSuffix);
        var partial = Path.Combine(inbox, $".{proposal.RequestId}.{Guid.NewGuid():N}.partial");
        EnsureFixedPath(root, target);
        EnsureFixedPath(root, partial);
        var bytes = JsonSerializer.SerializeToUtf8Bytes(proposal, CodexJson.Options);
        if (bytes.Length > CodexProposalFiles.MaximumProposalBytes)
        {
            throw FixtureProblem();
        }
        try
        {
            using (var stream = new FileStream(partial, FileMode.CreateNew, FileAccess.Write, FileShare.None))
            {
                stream.Write(bytes);
                stream.Flush(true);
            }
            EnsureFixedPath(root, target);
            EnsureFixedPath(root, partial);
            File.Move(partial, target, overwrite: false);
        }
        finally
        {
            try
            {
                EnsureFixedPath(root, partial);
                if (File.Exists(partial)) File.Delete(partial);
            }
            catch { /* Never follow a changed path to clean up a fixture. */ }
        }
    }

    private static void EnsureFixedPath(string root, string path)
    {
        var fullPath = Path.GetFullPath(path);
        if (!string.Equals(fullPath, root, StringComparison.OrdinalIgnoreCase) &&
            !fullPath.StartsWith(root + Path.DirectorySeparatorChar, StringComparison.OrdinalIgnoreCase))
        {
            throw FixtureProblem();
        }
        var current = fullPath;
        while (true)
        {
            try
            {
                if ((File.GetAttributes(current) & FileAttributes.ReparsePoint) != 0) throw FixtureProblem();
            }
            catch (FileNotFoundException) { }
            catch (DirectoryNotFoundException) { }
            if (string.Equals(current, root, StringComparison.OrdinalIgnoreCase)) break;
            current = Path.GetDirectoryName(current) ?? throw FixtureProblem();
        }
    }

    private static AppProblemException FixtureProblem() => new(AppProblem.Database(
        "Codex画面試験用の新規合成データを確認できませんでした。試作版を新しく起動してください。"));

    private sealed class SeedState
    {
        public bool Attempted { get; set; }
    }
}
