using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using KnowledgeApp.CSharp;

if (args.Length == 2 && args[0] == "--verify")
{
    UiBundleLocator.Resolve(args[1]);
    Console.WriteLine("PASS: adjacent UI manifest, complete file set and SHA-256 hashes.");
    return;
}
if (args.Length != 0) throw new ArgumentException("Only --verify <package directory> is supported.");
var root = Path.Combine(Path.GetTempPath(), "knowledgeapp-ui-check-" + Guid.NewGuid().ToString("D"));
Directory.CreateDirectory(root);
var passed = 0;
try
{
    Check("repository-independent adjacent UI", _ => { }, accept: true);
    Check("no ancestor fallback", package => Directory.Move(Path.Combine(package, "ui"), Path.Combine(package, "dist")));
    Check("manifest missing", package => File.Delete(Path.Combine(package, UiBundleLocator.ManifestName)));
    Check("index missing", package => File.Delete(Path.Combine(package, "ui", "index.html")));
    Check("lazy chunk missing", package => File.Delete(Path.Combine(package, "ui", "assets", "Lazy-abc123.js")));
    Check("entry chunk changed", package => File.AppendAllText(Path.Combine(package, "ui", "assets", "index-abc123.js"), "changed", new UTF8Encoding(false)));
    Check("unknown UI file", package => File.WriteAllText(Path.Combine(package, "ui", "unexpected.txt"), "synthetic", new UTF8Encoding(false)));
    Check("extra safe-extension chunk", package => File.WriteAllText(Path.Combine(package, "ui", "assets", "Injected-abc.js"), "synthetic", new UTF8Encoding(false)));
    Check("nested assets directory", package => Directory.CreateDirectory(Path.Combine(package, "ui", "assets", "nested")));
    Check("manifest future version", package => Rewrite(package, text => text.Replace("\"formatVersion\":1", "\"formatVersion\":2", StringComparison.Ordinal)));
    Check("manifest unknown property", package => Rewrite(package, text => text.Replace("\"formatVersion\":1", "\"formatVersion\":1,\"unexpected\":true", StringComparison.Ordinal)));
    Check("manifest traversal", package => Rewrite(package, text => text.Replace("assets/Lazy-abc123.js", "../Lazy-abc123.js", StringComparison.Ordinal)));
    Check("manifest invalid hash", package => Rewrite(package, text => text.Replace("\"sha256\":\"", "\"sha256\":\"x", StringComparison.Ordinal)));
    Console.WriteLine($"PASS: {passed} isolated UI bundle scenarios; no application or database opened.");
}
finally
{
    // Every entry here was generated by this check, with no link creation.
    var full = Path.GetFullPath(root);
    if (Path.GetDirectoryName(full) != Path.TrimEndingDirectorySeparator(Path.GetFullPath(Path.GetTempPath())) ||
        !Path.GetFileName(full).StartsWith("knowledgeapp-ui-check-", StringComparison.Ordinal)) throw new IOException("Unexpected test root.");
    Directory.Delete(full, recursive: true);
}

void Check(string name, Action<string> mutate, bool accept = false)
{
    var package = Path.Combine(root, "case-" + passed);
    Directory.CreateDirectory(Path.Combine(package, "ui", "assets"));
    var content = new Dictionary<string, string>
    {
        ["index.html"] = "<!doctype html><div id=\"root\"></div><script src=\"/assets/index-abc123.js\"></script><link href=\"/assets/index-abc123.css\">",
        ["assets/index-abc123.js"] = "import('./Lazy-abc123.js');",
        ["assets/index-abc123.css"] = "body{color:black}",
        ["assets/Lazy-abc123.js"] = "export default 'synthetic';"
    };
    var entries = new List<object>();
    foreach (var item in content)
    {
        var bytes = Encoding.UTF8.GetBytes(item.Value);
        File.WriteAllBytes(Path.Combine(package, "ui", item.Key.Replace('/', Path.DirectorySeparatorChar)), bytes);
        entries.Add(new { path = item.Key, size = bytes.Length, sha256 = Convert.ToHexString(SHA256.HashData(bytes)) });
    }
    File.WriteAllText(Path.Combine(package, UiBundleLocator.ManifestName),
        JsonSerializer.Serialize(new { formatVersion = 1, files = entries }), new UTF8Encoding(false));
    mutate(package);
    var accepted = false;
    try { UiBundleLocator.Resolve(package); accepted = true; }
    catch (Exception exception) when (exception is IOException or InvalidDataException or JsonException or InvalidOperationException or ArgumentException) { }
    if (accepted != accept) throw new InvalidOperationException("FAIL: " + name);
    passed++;
    Console.WriteLine("PASS: " + name);
}
void Rewrite(string package, Func<string, string> change)
{
    var path = Path.Combine(package, UiBundleLocator.ManifestName);
    File.WriteAllText(path, change(File.ReadAllText(path, Encoding.UTF8)), new UTF8Encoding(false));
}
